function(check_sse42_support target)
    include(CheckCXXCompilerFlag)
    string(TOLOWER "${CMAKE_SYSTEM_PROCESSOR}" TARGET_PROCESSOR_LOWER)
    # Clang-CL needs the same check for AVX2

    if (TARGET_PROCESSOR_LOWER MATCHES "^(aarch64|arm64|armv8)")
        if (CMAKE_CXX_COMPILER_ID MATCHES "GNU")
            check_cxx_compiler_flag("-march=armv8-a+crc" ARMCRC_SUPPORTED)
            if (ARMCRC_SUPPORTED)
                message(STATUS "Compiler supports ARM CRC32")
                target_compile_options(${target} PUBLIC -march=armv8-a+crc)
            else ()
                message(STATUS "Compiler does not support ARM CRC32")
            endif ()
        elseif (CMAKE_CXX_COMPILER_ID MATCHES "Clang")
            if (CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "GNU")
                check_cxx_compiler_flag("-march=armv8-a+crc" ARMCRC_SUPPORTED)
                if (ARMCRC_SUPPORTED)
                    message(STATUS "Compiler supports ARM CRC32")
                    target_compile_options(${target} PUBLIC -march=armv8-a+crc)
                else ()
                    message(STATUS "Compiler does not support ARM CRC32")
                endif ()
            else ()
                message(STATUS "ARM CRC32 checks are not configured for this Clang frontend")
            endif ()
        else ()
            message(STATUS "ARM CRC32 checks are not configured for compiler ${CMAKE_CXX_COMPILER_ID}")
        endif ()
    elseif (CMAKE_CXX_COMPILER_ID MATCHES "GNU")
           set(CMAKE_CXX_FLAGS_RELEASE "-O2")

           check_cxx_compiler_flag("-msse4.2" SSE4_2_SUPPORTED)
           if(SSE4_2_SUPPORTED)
               message(STATUS "Compiler supports SSE4.2")
               target_compile_definitions(${target} PUBLIC SSE42_SUPPORTED)
               target_compile_options(${target} PUBLIC -msse4.2)
           else()
               message(STATUS "Compiler does not support SSE4.2")
           endif()

    elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
        if (CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC") # clang-cl
            set(CMAKE_CXX_FLAGS_RELEASE "/O2")

            check_cxx_compiler_flag("/arch:AVX" SSE4_2_SUPPORTED)
            if(SSE4_2_SUPPORTED)
                message(STATUS "Compiler supports SSE4.2")
                target_compile_definitions(${target} PUBLIC SSE42_SUPPORTED)
                target_compile_options(${target} PUBLIC /arch:AVX)

            else()
                message(STATUS "Compiler does not support SSE4.2")
            endif()

        elseif (CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "GNU") # clang native
            set(CMAKE_CXX_FLAGS_RELEASE "-O2")

            check_cxx_compiler_flag("-msse4.2" SSE4_2_SUPPORTED)
            if(SSE4_2_SUPPORTED)
                message(STATUS "Compiler supports SSE4.2")
                target_compile_definitions(${target} PUBLIC SSE42_SUPPORTED)
                target_compile_options(${target} PUBLIC -msse4.2)
            else()
                message(STATUS "Compiler does not support SSE4.2")
            endif()

        endif()
    elseif(CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
           set(CMAKE_CXX_FLAGS_RELEASE "/O2")

           check_cxx_compiler_flag("/arch:AVX" SSE4_2_SUPPORTED)
           if(SSE4_2_SUPPORTED)
               message(STATUS "Compiler supports SSE4.2")
               target_compile_definitions(${target} PUBLIC SSE42_SUPPORTED)
               target_compile_options(${target} PUBLIC /arch:AVX)
           else()
               message(STATUS "Compiler does not support SSE4.2")
           endif()
    else()
        message(WARNING "Unsupported compiler.")
       endif()
endfunction()
