cmake_minimum_required(VERSION 3.28)
project(Deflate)

function(configure_pgo target)
    option(USE_PGO "Enable Profile-Guided Optimization" OFF)
    set(PGO_PHASE "GENERATE" CACHE STRING "Specify the PGO phase (GENERATE or USE)")

    if(USE_PGO)
        if(CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
            if(${PGO_PHASE} STREQUAL "GENERATE")
                message(STATUS "Configuring PGO for MSVC (profile generation)")
                target_compile_options(${target} PRIVATE /GL )
                target_link_options(${target} PRIVATE /LTCG /GENPROFILE)
            elseif(${PGO_PHASE} STREQUAL "USE")
                message(STATUS "Configuring PGO for MSVC (profile use)")
                target_compile_options(${target} PRIVATE /GL )
                target_link_options(${target} PRIVATE /LTCG /USEPROFILE)
            endif()
        elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
            if (CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC") # clang-cl
                if(${PGO_PHASE} STREQUAL "GENERATE")
                    message(STATUS "Configuring PGO for Clang-cl (profile generation)")
                    target_compile_options(${target} PRIVATE -fprofile-generate)
                    target_link_options(${target} PRIVATE -fprofile-generate)
                elseif(${PGO_PHASE} STREQUAL "USE")
                    message(STATUS "Configuring PGO for Clang-cl (profile use)")
                    target_compile_options(${target} PRIVATE -fprofile-use -fprofile-correction)
                    target_link_options(${target} PRIVATE -fprofile-use -fprofile-correction)
                endif()
            elseif (CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "GNU") # clang native
                if(${PGO_PHASE} STREQUAL "GENERATE")
                    message(STATUS "Configuring PGO for Clang (profile generation)")
                    target_compile_options(${target} PRIVATE -fprofile-generate)
                    target_link_options(${target} PRIVATE -fprofile-generate)
                elseif(${PGO_PHASE} STREQUAL "USE")
                    message(STATUS "Configuring PGO for Clang (profile use)")
                    target_compile_options(${target} PRIVATE -fprofile-use -fprofile-correction)
                    target_link_options(${target} PRIVATE -fprofile-use -fprofile-correction)
                endif()
            endif()
        else()
            message(WARNING "PGO is not supported for the current compiler.")
        endif()
    endif()
endfunction()